[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background = '#282433'
foreground = '#eee9fc'

[colors.cursor]
text = '#eee9fc'
cursor = '#eee9fc'

[colors.normal]
black   = '#282433'
red     = '#e965a5'
green   = '#b1f2a7'
yellow  = '#ebde76'
blue    = '#b1baf4'
magenta = '#e192ef'
cyan    = '#b3f4f3'
white   = '#eee9fc'

[colors.bright]
black   = '#3f3951'
red     = '#e965a5'
green   = '#b1f2a7'
yellow  = '#ebde76'
blue    = '#b1baf4'
magenta = '#e192ef'
cyan    = '#b3f4f3'
white   = '#eee9fc'
